language: node_js
node_js: "6.10.0"
dist: precise
sudo: false

env:
  global:
    - CF_TEST="false"
    - START_TIMEOUT=20000
    - TOTAL_TIMEOUT=120000

jobs:
  include:
    - &unit-tests
      stage: unit tests
      script: npm run build && npm run coveralls
      env:
        - DESCRIPTION="pouchdb"
    - <<: *unit-tests
      env:
        - DESCRIPTION="couchdb"
        - JOBS=1
        - DBCLIENT=abacus-couchclient
        - DB=http://localhost:5984
      services:
        - couchdb
    - <<: *unit-tests
      env:
        - DESCRIPTION="mongodb 2.6"
        - JOBS=1
        - DBCLIENT=abacus-mongoclient
        - DB=mongodb://localhost:27017
      addons:
        apt:
          sources:
            - mongodb-upstart
          packages:
            - mongodb-org-server=2.6.9
            - mongodb-org-shell=2.6.9
      install:
        - sleep 15
    - <<: *unit-tests
      env:
        - DESCRIPTION="mongodb 3.2"
        - JOBS=1
        - DBCLIENT=abacus-mongoclient
        - DB=mongodb://localhost:27017
      addons:
        apt:
          sources:
            - mongodb-upstart
          packages:
            - mongodb-org-server
            - mongodb-org-shell
      install:
        - sleep 15
    - &integration-tests
      stage: integration tests
      before_script: npm run provision
      script: travis_retry npm run citest -- --start-timeout $START_TIMEOUT --total-timeout $TOTAL_TIMEOUT
      env:
        - DESCRIPTION="pouchdb"
        - CI_TEST=itest
    - <<: *integration-tests
      env:
        - DESCRIPTION="couchdb"
        - JOBS=1
        - DBCLIENT=abacus-couchclient
        - DB=http://localhost:5984
        - CI_TEST=itest
      services:
        - couchdb
    - <<: *integration-tests
      env:
        - DESCRIPTION="mongodb 2.6"
        - JOBS=1
        - DBCLIENT=abacus-mongoclient
        - DB=mongodb://localhost:27017
        - CI_TEST=itest
      addons:
        apt:
          sources:
            - mongodb-upstart
          packages:
            - mongodb-org-server=2.6.9
            - mongodb-org-shell=2.6.9
      install:
        - sleep 15
    - <<: *integration-tests
      env:
        - DESCRIPTION="mongodb 3.2"
        - JOBS=1
        - DBCLIENT=abacus-mongoclient
        - DB=mongodb://localhost:27017
        - CI_TEST=itest
      addons:
        apt:
          sources:
            - mongodb-upstart
          packages:
            - mongodb-org-server
            - mongodb-org-shell
      install:
        - sleep 15
    - &extended-tests
      stage: extended tests
      before_script: npm run provision
      script: travis_retry npm run citest -- --start-timeout $START_TIMEOUT --total-timeout $TOTAL_TIMEOUT
      env:
        - DESCRIPTION="pouchdb"
        - CI_TEST=extended
    - <<: *extended-tests
      env:
        - DESCRIPTION="couchdb"
        - JOBS=1
        - DBCLIENT=abacus-couchclient
        - DB=http://localhost:5984
        - CI_TEST=extended
      services:
        - couchdb
    - <<: *extended-tests
      env:
        - DESCRIPTION="mongodb 2.6"
        - JOBS=1
        - DBCLIENT=abacus-mongoclient
        - DB=mongodb://localhost:27017
        - CI_TEST=extended
      addons:
        apt:
          sources:
            - mongodb-upstart
          packages:
            - mongodb-org-server=2.6.9
            - mongodb-org-shell=2.6.9
      install:
        - sleep 15
    - <<: *extended-tests
      env:
        - DESCRIPTION="mongodb 3.2"
        - JOBS=1
        - DBCLIENT=abacus-mongoclient
        - DB=mongodb://localhost:27017
        - CI_TEST=extended
      addons:
        apt:
          sources:
            - mongodb-upstart
          packages:
            - mongodb-org-server
            - mongodb-org-shell
      install:
        - sleep 15
    - &perf-tests
      stage: performance tests
      script: travis_retry npm run citest -- --start-timeout $START_TIMEOUT --total-timeout $TOTAL_TIMEOUT
      before_script: npm run provision
      env:
        - DESCRIPTION="pouchdb"
        - CI_TEST=perf
    - <<: *perf-tests
      env:
        - DESCRIPTION="couchdb"
        - JOBS=1
        - DBCLIENT=abacus-couchclient
        - DB=http://localhost:5984
        - CI_TEST=perf
      services:
        - couchdb
    - <<: *perf-tests
      env:
        - DESCRIPTION="mongodb 2.6"
        - JOBS=1
        - DBCLIENT=abacus-mongoclient
        - DB=mongodb://localhost:27017
        - CI_TEST=perf
      addons:
        apt:
          sources:
            - mongodb-upstart
          packages:
            - mongodb-org-server=2.6.9
            - mongodb-org-shell=2.6.9
      install:
        - sleep 15
    - <<: *perf-tests
      env:
        - DESCRIPTION="mongodb 3.2"
        - JOBS=1
        - DBCLIENT=abacus-mongoclient
        - DB=mongodb://localhost:27017
        - CI_TEST=perf
      addons:
        apt:
          sources:
            - mongodb-upstart
          packages:
            - mongodb-org-server
            - mongodb-org-shell
      install:
        - sleep 15
    - stage: deploy
      script: travis_retry npm run cftest -- --start-timeout $START_TIMEOUT --total-timeout $TOTAL_TIMEOUT

notifications:
  irc:
    use_notice: true
    on_success: change
    on_failure: change
    channels:
    - chat.freenode.net#cf-abacus
  slack:
    secure: ZanKYSBhluB1KMzd003+7PiASbgKKwNKl3Ucc4B3wuFWdpdNp/K4/AxPnjGTIRvFtyMtvHf+392bURxBWQMypyW+FMQXGOnJD+bVrVhzxAVc10smkT59NcemWry4gwHQlPF22MB+EoYqnsqXLFltMalEzRC+sjiXED7ZguUD7SJquRmydIlBHkU8hqbGwLg78oNS9WarhvikjsrKchNfSLe3pOMCspgpNQ4KAY+KdrUB4hAqlaul+WdUz3ivaazQZXtV4Rq9i9ADHh7WgyF1SYSWrqAQXuiM5KnwaD/m3lL01F9wxfK/NbuPH6gYg1XZhxhGBw4uT+udWZ3YFQy/G3YRu8URx1er+evI8JMhjjO+BIO1K3geEQ1Kmu1FdCeuhtbWVo0fokLkQGISVc0llgjIC1PR8NMMtDHTvUiK44F8GRONnT9tmKTyJBfRCwD23NV6oWPH2LL6uCya4CmveaKSz1G3IjulGGCdxCkIMjraw/J7fkg8INc9lhEl8Uim7pIJkDjuNp8zf4AGOTUpX1O9RMMvQkWqmpkf4Gug/JFcMAiX1WEQ6/5M3Q3HBLW3fe2DEp1H+A9RakA/QMGIytFm9oAnUGhad20wmvPlAaWxY+UpLHH/VNx7X5k/DhygSKnORuHLuR821LXCuLROEh5dtxdZckxXWFJH11xXhlw=
