language: node_js
node_js:
 - "8.1.3"
 - "node"
dist: trusty
sudo: false
git:
  depth: 3

before_install:
  - npm i -g npm@latest-4

env:
  global:
    - CF_TEST="false"
    - START_TIMEOUT=20000
    - TOTAL_TIMEOUT=120000

matrix:
  include:
    - env:
      - DESCRIPTION="unit-tests-pouchdb"
      script:
        - npm run build && npm run coveralls
    - env:
      - DESCRIPTION="unit-tests-couchdb"
      - DBCLIENT=abacus-couchclient
      - DB=http://localhost:5984
      services:
        - couchdb
      script:
        - npm run build && npm run coveralls
    - env:
      - DESCRIPTION="unit-tests-mongodb"
      - DBCLIENT=abacus-mongoclient
      - DB=mongodb://localhost:27017
      services:
        - mongodb
      script:
        - npm run build && npm run coveralls

    - env:
      - DESCRIPTION="itests-pouchdb"
      - CI_TEST=itest
      - JOBS=1
      script:
        - npm run provision
        - travis_retry npm run citest -- --start-timeout $START_TIMEOUT --total-timeout $TOTAL_TIMEOUT
    - env:
      - DESCRIPTION="itests-couchdb"
      - DBCLIENT=abacus-couchclient
      - DB=http://localhost:5984
      - CI_TEST=itest
      - JOBS=1
      services:
        - couchdb
      script:
        - npm run provision
        - travis_retry npm run citest -- --start-timeout $START_TIMEOUT --total-timeout $TOTAL_TIMEOUT
    - env:
      - DESCRIPTION="itests-mongodb"
      - DBCLIENT=abacus-mongoclient
      - DB=mongodb://localhost:27017
      - CI_TEST=itest
      - JOBS=1
      services:
        - mongodb
      script:
        - npm run provision
        - travis_retry npm run citest -- --start-timeout $START_TIMEOUT --total-timeout $TOTAL_TIMEOUT

    - env:
      - DESCRIPTION="extended-tests-pouchdb"
      - CI_TEST=extended
      - JOBS=1
      script:
        - npm run provision
        - travis_retry npm run citest -- --start-timeout $START_TIMEOUT --total-timeout $TOTAL_TIMEOUT
    - env:
      - DESCRIPTION="extended-tests-couchdb"
      - DBCLIENT=abacus-couchclient
      - DB=http://localhost:5984
      - CI_TEST=extended
      - JOBS=1
      services:
        - couchdb
      script:
        - npm run provision
        - travis_retry npm run citest -- --start-timeout $START_TIMEOUT --total-timeout $TOTAL_TIMEOUT
    - env:
      - DESCRIPTION="extended-tests-couchdb"
      - DBCLIENT=abacus-mongoclient
      - DB=mongodb://localhost:27017
      - CI_TEST=extended
      - JOBS=1
      services:
        - mongodb
      script:
        - npm run provision
        - travis_retry npm run citest -- --start-timeout $START_TIMEOUT --total-timeout $TOTAL_TIMEOUT

    - env:
      - DESCRIPTION="perf-tests-pouchdb"
      - CI_TEST=perf
      - JOBS=1
      script:
        - npm run provision
        - travis_retry npm run citest -- --start-timeout $START_TIMEOUT --total-timeout $TOTAL_TIMEOUT
    - env:
      - DESCRIPTION="perf-tests-couchdb"
      - DBCLIENT=abacus-couchclient
      - DB=http://localhost:5984
      - CI_TEST=perf
      - JOBS=1
      services:
        - couchdb
      script:
        - npm run provision
        - travis_retry npm run citest -- --start-timeout $START_TIMEOUT --total-timeout $TOTAL_TIMEOUT
    - env:
      - DESCRIPTION="perf-tests-couchdb"
      - DBCLIENT=abacus-mongoclient
      - DB=mongodb://localhost:27017
      - CI_TEST=perf
      - JOBS=1
      services:
        - mongodb
      script:
        - npm run provision
        - travis_retry npm run citest -- --start-timeout $START_TIMEOUT --total-timeout $TOTAL_TIMEOUT

notifications:
  irc:
    use_notice: true
    on_success: change
    on_failure: change
    channels:
    - chat.freenode.net#cf-abacus
  slack:
    secure: ZanKYSBhluB1KMzd003+7PiASbgKKwNKl3Ucc4B3wuFWdpdNp/K4/AxPnjGTIRvFtyMtvHf+392bURxBWQMypyW+FMQXGOnJD+bVrVhzxAVc10smkT59NcemWry4gwHQlPF22MB+EoYqnsqXLFltMalEzRC+sjiXED7ZguUD7SJquRmydIlBHkU8hqbGwLg78oNS9WarhvikjsrKchNfSLe3pOMCspgpNQ4KAY+KdrUB4hAqlaul+WdUz3ivaazQZXtV4Rq9i9ADHh7WgyF1SYSWrqAQXuiM5KnwaD/m3lL01F9wxfK/NbuPH6gYg1XZhxhGBw4uT+udWZ3YFQy/G3YRu8URx1er+evI8JMhjjO+BIO1K3geEQ1Kmu1FdCeuhtbWVo0fokLkQGISVc0llgjIC1PR8NMMtDHTvUiK44F8GRONnT9tmKTyJBfRCwD23NV6oWPH2LL6uCya4CmveaKSz1G3IjulGGCdxCkIMjraw/J7fkg8INc9lhEl8Uim7pIJkDjuNp8zf4AGOTUpX1O9RMMvQkWqmpkf4Gug/JFcMAiX1WEQ6/5M3Q3HBLW3fe2DEp1H+A9RakA/QMGIytFm9oAnUGhad20wmvPlAaWxY+UpLHH/VNx7X5k/DhygSKnORuHLuR821LXCuLROEh5dtxdZckxXWFJH11xXhlw=
